packages:
  - .
  - amplify
  - web

overrides:
  '@eslint/eslintrc>ajv': ^6.12.4
  '@smithy/config-resolver@<4.4.0': '>=4.4.0'
  ajv@<8.18.0: '>=8.18.0'
  diff@<8.0.3: '>=8.0.3'
  eslint>ajv: ^6.12.4
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  minimatch@<10.2.1: '>=10.2.1'
  seroval@<1.4.1: '>=1.4.1'
